# 4ccconv
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man1/4ccconv.1
complete -c 4ccconv -s x -d 'print hexadecimal representation of number as a 4cc'
complete -c 4ccconv -s u -d 'print unsigned integer representation of number as a 4cc'
complete -c 4ccconv -s 4 -d 'print 4 code char representation of number (0x prefix will be interpreted as …'

