# @TSET@
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man1/@TSET@.1
complete -c @TSET@ -s I -d 'Do not send the terminal or tab initialization strings to the terminal'
complete -c @TSET@ -s i -d 'Set the interrupt character to ch'
complete -c @TSET@ -s k -d 'Set the line kill character to ch'
complete -c @TSET@ -s m -d 'Specify a mapping from a port type to a terminal'
complete -c @TSET@ -s Q -d 'Do not display any values for the erase, interrupt and line kill characters'
complete -c @TSET@ -s q -d 'The terminal type is displayed to the standard output, and the terminal is no…'
complete -c @TSET@ -s r -d 'Print the terminal type to the standard error output'
complete -c @TSET@ -s s -d 'Print the sequence of shell commands to initialize the environment variable T…'
complete -c @TSET@ -s V -d 'reports the version of ncurses which was used in this program, and exits'
complete -c @TSET@ -s c -d 'Set control characters and modes'
complete -c @TSET@ -s e -d 'Set the erase character to ch'
complete -c @TSET@ -s w -d 'Resize the window to match the size deduced via setupterm'

