# adacurses-config
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man1/adacurses-config.1
complete -c adacurses-config -l cflags -d 'echos the gnat (Ada compiler) flags needed to compile with AdaCurses'
complete -c adacurses-config -l libs -d 'echos the gnat libraries needed to link with AdaCurses'
complete -c adacurses-config -l version -d 'echos the release+patchdate version of the ncurses libraries used to configur…'
complete -c adacurses-config -l help -d 'prints a list of the adacurses-config script\'s options.  SEE ALSO curses(3X)'

