# afhash
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man1/afhash.1
complete -c afhash -s h -d 'print help text'
complete -c afhash -s w -d 'write hash code to audio file'
complete -c afhash -s x -d 'print hash code from audio file (if present)'
complete -c afhash -s c -d 'compare hash codes from two audio files El'

