# amt
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man8/amt.8
complete -c amt -s m -d 'Skip the memory test'
complete -c amt -s p -d 'Skip the privileged instructions test'
complete -c amt -s q -d 'Suppress the screen output'
complete -c amt -s s -d 'Skip the memory separation and protection test'

