# apfs_condenser
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man8/apfs_condenser.8
complete -c apfs_condenser -s s -d 'If compaction succeeds, the snapshot will be deleted'
complete -c apfs_condenser -s v -d 'Increase verbosity of the output'
complete -c apfs_condenser -s w -d 'Force the compaction to abort after the supplied timeout in seconds'

