# appleeventsd
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man8/appleeventsd.8
complete -c appleeventsd -l server
complete -c appleeventsd -l noStartupNotification

