# atrun
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man8/atrun.8
complete -c atrun -s l -d 'Specify a limiting load factor, over which batch jobs should not be run, inst…'
complete -c atrun -s d -d 'Debug; print error messages to standard error instead of using syslog 3'

