# bioutil
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man1/bioutil.1
complete -c bioutil -s r -d 'Read biometrics configuration'
complete -c bioutil -s w -d 'Write biometrics configuration'
complete -c bioutil -s s -d 'Indicates that system-wide configuration is to be read/written (user-specific…'
complete -c bioutil -s f -d 'Enables (1) or disables (0) overall biometrics functionality (system-wide con…'
complete -c bioutil -s u -d 'Enables (1) or disables (0) biometrics for unlock'
complete -c bioutil -s a -d 'Enables (1) or disables (0) biometrics for ApplePay (user-specific configurat…'
complete -c bioutil -s o -d 'Sets biometric timeout (in seconds, system-wide configuration only)'
complete -c bioutil -l btimeout -d 'Sets biometric timeout (in seconds, system-wide configuration only)'
complete -c bioutil -l mtimeout -d 'Sets match timeout (in seconds, system-wide configuration only)'
complete -c bioutil -l ptimeout -d 'Sets passcode input timeout (in seconds, system-wide configuration only)'
complete -c bioutil -s c -d 'Provides number of enrolled biometric templates of the current user or of all…'
complete -c bioutil -s p -d 'Deletes all enrolled biometric templates of the current user or of all users …'
complete -c bioutil -s d -d 'Deletes all enrolled biometric templates of the user with given user ID (must…'

