# bundle-init
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man1/bundle-init.1
complete -c bundle-init -l gemspec -d 'Use the specified . gemspec to create the [Gemfile(5)][Gemfile(5)]'

