# bundle-exec
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man1/bundle-exec.1
complete -c bundle-exec -l keep-file-descriptors -d 'Exec in Ruby 2. 0 began discarding non-standard file descriptors'

