# bundle-show
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man1/bundle-show.1
complete -c bundle-show -l paths -d 'List the paths of all gems that are required by your [Gemfile(5)][Gemfile(5)]…'

