# bundle-remove
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man1/bundle-remove.1
complete -c bundle-remove -l install -d 'Runs bundle install after the given gems have been removed from the Gemfile, …'

