# bundle-platform
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man1/bundle-platform.1
complete -c bundle-platform -l ruby -d 'It will display the ruby directive information, so you don\'t have to parse it…'

