# cd9660.util
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man8/cd9660.util.8
complete -c 'cd9660.util' -s m -d mount
complete -c 'cd9660.util' -s p -d 'probe for mounting'
complete -c 'cd9660.util' -s u -d 'unmount El Pp mountflags above are either: -bullet It removable or fixed It r…'

