# colldef
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man1/colldef.1
complete -c colldef -s I -d 'Set directory name where charmap files can be found, current directory by def…'
complete -c colldef -s o -d 'Set output file name, LC_COLLATE by default'

