# compression_tool
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man1/compression_tool.1
complete -c compression_tool -o encode -d 'Encode (compress) the input'
complete -c compression_tool -o decode -d 'Decode (uncompress) the input'
complete -c compression_tool -o '\\-a' -d 'Set the compression algorithm, valid options are \\fBzlib\\fR, \\fBlzma\\fR, \\fBl…'
complete -c compression_tool -o '\\-A' -d 'Enable block compression, and set compression algorithm, valid options are \\f…'
complete -c compression_tool -o '\\-b' -d 'Set block size for block compression'
complete -c compression_tool -o '\\-t' -d 'Set the number of worker threads to use for block compression/decompression'
complete -c compression_tool -o '\\-i' -d 'Input file.  If omitted, read from standard input'
complete -c compression_tool -o '\\-o' -d 'Output file.  If omitted, write to standard output'
complete -c compression_tool -o '\\-v' -d 'Increase verbosity.  Default is silent operation'
complete -c compression_tool -o '\\-h' -d 'Print usage and exit'

