# coreBluetoothUtil
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man1/coreBluetoothUtil.1
complete -c coreBluetoothUtil -s a -d 'Description of -a flag'
complete -c coreBluetoothUtil -s b -d 'Description of -b flag \\" Ends the list Pp FILES                \\" File used …'

