# crontab
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man1/crontab.1
complete -c crontab -s u -d 'Specify the name of the user whose crontab is to be tweaked'
complete -c crontab -s l -d 'Display the current crontab on standard output'
complete -c crontab -s r -d 'Remove the current crontab'
complete -c crontab -s e -d 'Edit the current crontab using the editor specified by the VISUAL or EDITOR e…'

