# cryptexctl-install
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man1/cryptexctl-install.1
complete -c cryptexctl-install -s V -d 'The name of the cryptex CRYPTEX-DIRECTORY The path to the cryptex bundle dire…'

