# cryptexctl-generate-trust-cache
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man1/cryptexctl-generate-trust-cache.1
complete -c cryptexctl-generate-trust-cache -s o -d 'The file to which the trust cache should be written, will be replaced if it a…'
complete -c cryptexctl-generate-trust-cache -s t -d 'The type of trust cache to produce'
complete -c cryptexctl-generate-trust-cache -s b -d 'The path to an existing trust cache of any type whose cdhashes should be inco…'

