# cryptexctl-log
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man1/cryptexctl-log.1
complete -c cryptexctl-log -s d -d 'Display debug messages passes the -d option to log 1 Pc'
complete -c cryptexctl-log -s c -d 'Use the compact log style Po passes the --style compact option to log 1 Pc <s…'

