# cryptexctl-list
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man1/cryptexctl-list.1
complete -c cryptexctl-list -s l -d 'Fetch the list of installed cryptexes in a lossy way which will not communica…'

