# cryptexctl-create
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man1/cryptexctl-create.1
complete -c cryptexctl-create -s i -d 'A reverse-ICANN identitifer for the cryptex'
complete -c cryptexctl-create -s v -d 'The CFBundleVersion-style version number for the cryptex'
complete -c cryptexctl-create -s V -d 'The name of the cryptex PATH-TO-DMG The path to the disk image file from whic…'
complete -c cryptexctl-create -s o -d 'The directory to which the cryptex should be written'
complete -c cryptexctl-create -s r -d 'Replace the cryptex in OUTPUT-DIRECTORY if it already exists'
complete -c cryptexctl-create -s H -d 'Use the host\'s identity for the personalization; if specified all other ident…'
complete -c cryptexctl-create -s z -d 'Cryptex will be created as a research cryptex with the cpxd tag'

