# cryptexctl-path
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man1/cryptexctl-path.1
complete -c cryptexctl-path -s c -d 'Limits results to the cryptex with the specified Bundle ID'
complete -c cryptexctl-path -s s -d 'Specifies the UUID of the session you want to search instead of the current u…'
complete -c cryptexctl-path -s S -d 'Provided a colon delimited list of paths, returns all instances of those subp…'
complete -c cryptexctl-path -s p -d 'Use a default SEARCH_PATH appropriate for inserting into the PATH environment…'

