# cryptexctl-dump-trust-cache
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man1/cryptexctl-dump-trust-cache.1
complete -c cryptexctl-dump-trust-cache -s i -d 'Indicate that the file is a wrapped Image4 payload El -tag -width -indent TRU…'

