# cryptexctl-personalize
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man1/cryptexctl-personalize.1
complete -c cryptexctl-personalize -s V -d 'The name of the cryptex PATH-TO-CRYPTEX-BUNDLE The path to the cryptex bundle…'
complete -c cryptexctl-personalize -s o -d 'The directory to which the cryptex should be written'
complete -c cryptexctl-personalize -s r -d 'Replace the cryptex in OUTPUT-DIRECTORY if it already exists'
complete -c cryptexctl-personalize -s I -d 'Path to a property list whose root node is a dictionary containing a set of k…'
complete -c cryptexctl-personalize -s H -d 'Use the host\'s identity for the personalization; if specified all other ident…'
complete -c cryptexctl-personalize -s M -d 'Personalize with the AMNM entitlement'
complete -c cryptexctl-personalize -s z -d 'Cryptex will be created as a research cryptex with the cpxd tag'

