# csnameddata
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man8/csnameddata.8
complete -c csnameddata -s f -d 'when displaying an item, don\'t truncate the data display'
complete -c csnameddata -o full -d 'when displaying an item, don\'t truncate the data display'
complete -c csnameddata -s v -d 'display more verbose status'
complete -c csnameddata -l verbose -d 'display more verbose status El COMMANDS Each command and any arguments are ha…'

