# dbiprof5.34
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man1/dbiprof5.34.1
complete -c 'dbiprof5.34' -l number -d 'Produce this many items in the report.   Defaults to 10'
complete -c 'dbiprof5.34' -l sort -d 'Sort results by the given field'
complete -c 'dbiprof5.34' -l reverse -d 'Reverses the selected sort'
complete -c 'dbiprof5.34' -l match -d 'Consider only items where the specified key matches the given value'
complete -c 'dbiprof5.34' -l exclude -d 'Remove items for where the specified key matches the given value'
complete -c 'dbiprof5.34' -l case-sensitive -d 'Using this option causes --match and --exclude to work case-sensitively'
complete -c 'dbiprof5.34' -l delete -d 'Sets the \\f(CW\\*(C`DeleteFiles\\*(C\' option to DBI::ProfileData which causes t…'
complete -c 'dbiprof5.34' -l dumpnodes -d 'Print the list of nodes in the form of a perl data structure'

