# demandoc
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man1/demandoc.1
complete -c demandoc -s w -d 'Output a word list.  This outputs each word of text on its own line'

