# diff3
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man1/diff3.1
complete -c diff3 -s 3 -d 'Produces an output script suitable for ed 1 with changes specific only to fil…'
complete -c diff3 -s A -d 'Output all changes, bracketing conflicts'
complete -c diff3 -s a -d 'Treat all files as ASCII'
complete -c diff3 -s E
complete -c diff3 -s X -d 'Similar to e and x, respectively, but treat overlapping changes (i. e'
complete -c diff3 -s e -d 'Produces output in a form suitable as an input script for the ed 1 utility'
complete -c diff3 -l help -d 'Prints usage information and exits'
complete -c diff3 -s i -d 'Appends \'w\' and \'q\' ed 1 commands'
complete -c diff3 -s L -d 'Defines labels to print instead of file names file1, file2 and file3'
complete -c diff3 -s m -d 'Merge output instead of generating ed script'
complete -c diff3 -s T -d 'In the normal listing, use a tab instead of two spaces at the beginning of ea…'
complete -c diff3 -s x -d 'Produces an output script suitable for ed 1 with changes specific only to all…'
complete -c diff3 -l diff-program -d 'Use program instead of the default diff 1 to compare files'
complete -c diff3 -l strip-trailing-cr -d 'Strip trailing carriage return on input files'
complete -c diff3 -l version -d 'Prints version information and exits'

