# diskarbitrationd
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man8/diskarbitrationd.8
complete -c diskarbitrationd -s d -d 'Report detailed information in /var/log/diskarbitrationd. log'

