# dyld
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man1/dyld.1
complete -c dyld -s L -d 'option to  otool (1) to discover the frameworks and shared libraries that the…'

