# dynamic_pager
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man8/dynamic_pager.8
complete -c dynamic_pager -s F -d 'The base name of the filename to use for the swapfiles'

