# ed
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man1/ed.1
complete -c ed -s s -d 'Suppress diagnostics'
complete -c ed -s p -d 'Specify a command prompt.  This may be toggled on and off with the P command'

