# fileproviderctl
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man1/fileproviderctl.1
complete -c fileproviderctl -s h -d 'Display a friendly help message'

