# git-version
# Autogenerated from man page /Library/Developer/CommandLineTools/usr/share/man/man1/git-version.1
complete -c git-version -l build-options -d 'Include additional information about how git was built for diagnostic purposes'

