# gzexe
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man1/gzexe.1
complete -c gzexe -s d -d 'Decompress executables previously compressed by gzexe'

