# head
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man1/head.1
complete -c head -s c -d 'Print bytes of each of the specified files'
complete -c head -s n -d 'Print count lines of each of the specified files'

