# htdigest
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man1/htdigest.1
complete -c htdigest -s c -d 'Create the passwdfile.  If passwdfile already exists, it is deleted first'

