# iconutil
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man1/iconutil.1
complete -c iconutil -s c -d 'Given the argument iconset, iconutil converts the source \''
complete -c iconutil -s o -d 'Overrides the default output file name that iconutil uses to save the convert…'

