# iconv
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man1/iconv.1
complete -c iconv -s c -d 'Prevent output of any invalid characters'
complete -c iconv -s f -d 'Specifies the source codeset name as from_name'
complete -c iconv -s l -d 'Lists available codeset names'
complete -c iconv -s s -d Silent
complete -c iconv -s t -d 'Specifies the destination codeset name as to_name'

