# imptrace
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man1/imptrace.1
complete -c imptrace -s i -d 'Show internal kernel boosts'
complete -c imptrace -s s -d 'Show stacks for internal boosts'
complete -c imptrace -s p -d 'Limit events to the process identified by pid'
complete -c imptrace -s d -d 'Display raw Dtrace output; do not reformat timestamps and sort output'

