# kdcsetup
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man8/kdcsetup.8
complete -c kdcsetup -s v -d 'Controls the amount of output generated by kdcsetup'
complete -c kdcsetup -s a -d 'Name of a directory administrator authorized to make changes in Open Directory'
complete -c kdcsetup -s p -d 'The password for the above admin.   Required parameter'

