# lastcomm
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man1/lastcomm.1
complete -c lastcomm -s f -d 'Read from file rather than the default accounting file'
complete -c lastcomm -s w -d 'Use as many columns as needed to print the output instead of limiting it to 80'

