# mddiagnose
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man8/mddiagnose.8
complete -c mddiagnose -s h -d 'Print full usage'
complete -c mddiagnose -s m -d 'Gather a subset of the normal report'
complete -c mddiagnose -s f -d 'Write the diagnostic to the specified path'
complete -c mddiagnose -s p -d 'Gather Spotlight permissions and filter information'

