# mkbom
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man8/mkbom.8
complete -c mkbom -s h -d 'print full usage'
complete -c mkbom -s s -d 'create a simplified bom containing only file paths'
complete -c mkbom -s i -d 'use the information in filelist, one entry per line, to construct the bom file'

