# mkfile
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man8/mkfile.8
complete -c mkfile -s n -d 'Create an empty filename'
complete -c mkfile -s v -d 'Verbose.  Report the names and sizes of created files'

