# mkfifo
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man1/mkfifo.1
complete -c mkfifo -s m -d 'Set the file permission bits of the created fifos to the specified mode, igno…'

