# mklocale
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man1/mklocale.1
complete -c mklocale -s d -d 'Turns on debugging messages'
complete -c mklocale -s o -d 'Specify output file'

