# mlserviced
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man1/mlserviced.1
complete -c mlserviced -s a -d 'Description of -a flag'
complete -c mlserviced -s b -d 'Description of -b flag \\" Ends the list Pp FILES                \\" File used …'

