# mount_fdesc
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man8/mount_fdesc.8
complete -c mount_fdesc -s o -d 'Options are specified with a o flag followed by a comma separated string of o…'

