# mount_virtiofs
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man8/mount_virtiofs.8
complete -c mount_virtiofs -s r -d 'Mount file system as read-only'
complete -c mount_virtiofs -s u -d 'Set the owner of the files in the file system to uid'
complete -c mount_virtiofs -s g -d 'Set the group of the files in the file system to gid'

