# nslookup
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man1/nslookup.1
complete -c nslookup -o version -d 'option causes nslookup to print the version number and immediately exits'

