# odmigrationtool
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man1/odmigrationtool.1
complete -c odmigrationtool -o source -d 'source volume or path to migrate from'
complete -c odmigrationtool -o target -d 'destination volume or path to mirage to'

