# path_helper
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man8/path_helper.8
complete -c path_helper -s c -d 'Generate C-shell commands on stdout'
complete -c path_helper -s s -d 'Generate Bourne shell commands on stdout'

