# pathchk
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man1/pathchk.1
complete -c pathchk -s p -d 'Perform portability checks on the specified pathname arguments'
complete -c pathchk -s P -d 'In addition to the default or p checks, write a diagnostic for each argument …'

