# pbcopy
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man1/pbcopy.1
complete -c pbcopy -o pboard -d 'specifies which pasteboard to copy to or paste from'
complete -c pbcopy -o Prefer -d 'tells pbpaste what type of data to look for in the pasteboard first'

