# pl
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man1/pl.1
complete -c pl -l input -d 'Cause pl to use the specified file as input'
complete -c pl -l output -d 'Cause pl to use the specified file as output'

