# ppdhtml
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man1/ppdhtml.1
complete -c ppdhtml -s D -d 'Sets the named variable for use in the source file'
complete -c ppdhtml -s I -d 'Specifies an alternate include directory'

