# ppdi
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man1/ppdi.1
complete -c ppdi -s I -d 'Specifies an alternate include directory'
complete -c ppdi -s o -d 'Specifies the PPD source file to update'

