# ppdpo
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man1/ppdpo.1
complete -c ppdpo -s D -d 'Sets the named variable for use in the source file'
complete -c ppdpo -s I -d 'Specifies an alternate include directory'
complete -c ppdpo -s o -d 'Specifies the output file.  The supported extensions are . po or . po'

