# psm
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man1/psm.1
complete -c psm -s d -d 'specify a disk to operate on <disk3s5>'
complete -c psm -s s -d 'specify a specifc slot number'
complete -c psm -s v -d 'will make psm more verbose'

