# pwd
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man1/pwd.1
complete -c pwd -s L -d 'Display the logical current working directory'
complete -c pwd -s P -d 'Display the physical current working directory (all symbolic links resolved)'

