# quotaoff
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man8/quotaoff.8
complete -c quotaoff -s a -d 'If the a flag is supplied in place of any filesystem names, quotaoff quotaon …'
complete -c quotaoff -s g -d 'Only group quotas will be enabled/disabled.  The mount option file, . quota'
complete -c quotaoff -s u -d 'Only user quotas will be enabled/disabled.  The mount option file, . quota'
complete -c quotaoff -s v -d 'Causes quotaoff quotaon and quotaoff quotaoff to print a message for each fil…'

