# rmdir
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man1/rmdir.1
complete -c rmdir -s p -d 'Each directory argument is treated as a pathname of which all components will…'
complete -c rmdir -s v -d 'Be verbose, listing each directory as it is removed'

