# rpc.lockd
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man8/rpc.lockd.8
complete -c 'rpc.lockd' -s d -d 'The d option causes debugging information to be written to syslog, recording …'
complete -c 'rpc.lockd' -s g -d 'The g option allows to specify the grace period (in seconds)'
complete -c 'rpc.lockd' -s x -d 'The x option tells rpc'

