# rpcinfo
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man8/rpcinfo.8
complete -c rpcinfo -s T -d 'Specify the netid to use.  Supported netids are udp, tcp, udp6, and tcp6'
complete -c rpcinfo -s h -d 'Print out the synopsis of this program'

