# scselect
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man8/scselect.8
complete -c scselect -s n -d 'Delay changing the system\'s location until the next system boot (or the next …'

