# shazam-custom-catalog-export
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man1/shazam-custom-catalog-export.1
complete -c shazam-custom-catalog-export -s i -l input -d 'Path to an existing custom catalog file to be exported to disk'
complete -c shazam-custom-catalog-export -s o -l output -d 'Path to a directory to export the contents of a custom catalog to'

