# shazam-custom-catalog-display
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man1/shazam-custom-catalog-display.1
complete -c shazam-custom-catalog-display -s i -l input -d 'Path to an existing custom catalog file to be displayed'
complete -c shazam-custom-catalog-display -s p -l properties -d 'A comma separated list of media item properties to display'

