# shortcuts
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man1/shortcuts.1
complete -c shortcuts -o '\\-input' -d 'The shortcut file to sign'
complete -c shortcuts -o '\\-output' -d 'Output path for the signed shortcut file.  El Pp'

