# shutdown
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man8/shutdown.8
complete -c shutdown -s h -d 'The system is halted and powered off at the specified time'
complete -c shutdown -s p -d 'This flag is the equivalent of h'
complete -c shutdown -s r -d 'The system is rebooted at the specified time'
complete -c shutdown -s s -d 'The system is put to sleep at the specified time'
complete -c shutdown -s k -d 'Kick everybody off'
complete -c shutdown -s o -d 'If one of the h or r options are specified, shutdown will execute halt 8 or r…'
complete -c shutdown -s n -d 'If the o option is specified, prevent the file system cache from being flushe…'
complete -c shutdown -s u -d 'The system is halted up until the point of removing system power, but waits b…'

