# smbdiagnose
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man8/smbdiagnose.8
complete -c smbdiagnose -s h -d 'Print full usage'
complete -c smbdiagnose -s f -d 'Write the diagnostic to the specified path.  The default is ~/Desktop'
complete -c smbdiagnose -s s -d 'Collect sysdiagnose 1 information'

