# snmpstatus
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man1/snmpstatus.1
complete -c snmpstatus -o Cf -d 'option is given, see below), but this variable will then be missing from the …'

