# snmptrap
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man1/snmptrap.1
complete -c snmptrap -o Ci -d 'is added to the command line flags of snmptrap, it sends an INFORM-PDU, expec…'

