# sntpd
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man8/sntpd.8
complete -c sntpd -s L -d 'Overwrite any existing state with a header describing a stratum 1 uncalibrate…'
complete -c sntpd -s z -d 'Specify where to get the header data from'

