# suexec
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man8/suexec.8
complete -c suexec -s V -d 'If you are root, this option displays the compile options of suexec'

