# sw_vers
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man1/sw_vers.1
complete -c sw_vers -l productName -d 'Print only the value of the ProductName property'
complete -c sw_vers -l productVersion -d 'Print only the value of the ProductVersion property'
complete -c sw_vers -l productVersionExtra -d 'Print only the value of the ProductVersionExtra property'
complete -c sw_vers -l buildVersion -d 'Print only the value of the BuildVersion property'
complete -c sw_vers -o productName -d 'El Pp FILES -tag -width "/System/Library/CoreServices/SystemVersion'

