# tapi-reexport
# Autogenerated from man page /Library/Developer/CommandLineTools/usr/share/man/man1/tapi-reexport.1
complete -c tapi-reexport -o arch
complete -c tapi-reexport -o macosx_version_min
complete -c tapi-reexport -o ios_version_min
complete -c tapi-reexport -o watchos_version_min
complete -c tapi-reexport -o tvos_version_min -d 'This is set to indicate the oldest platform version that that the output is t…'
complete -c tapi-reexport -l help

