# tapi-installapi
# Autogenerated from man page /Library/Developer/CommandLineTools/usr/share/man/man1/tapi-installapi.1
complete -c tapi-installapi -o target
complete -c tapi-installapi -o arch
complete -c tapi-installapi -o mtargetos -d 'Specifies platform and deployment target to use for parsing header files'
complete -c tapi-installapi -o macosx_version_min
complete -c tapi-installapi -o ios_version_min
complete -c tapi-installapi -o watchos_version_min
complete -c tapi-installapi -o tvos_version_min -d 'This is set to indicate the oldest platform version that that the output is t…'
complete -c tapi-installapi -o fapplication-extension -d 'ignored if -fapplication-extension or -fno-application-extension are specifie…'

