# tapi-analyze
# Autogenerated from man page /Library/Developer/CommandLineTools/usr/share/man/man1/tapi-analyze.1
complete -c tapi-analyze -l target
complete -c tapi-analyze -s o
complete -c tapi-analyze -s v

