# tee
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man1/tee.1
complete -c tee -s a -d 'Append the output to the files rather than overwriting them'
complete -c tee -s i -d 'Ignore the SIGINT signal'

