# truncate
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man1/truncate.1
complete -c truncate -s c -d 'Do not create files if they do not exist'
complete -c truncate -s r -d 'Truncate or extend files to the length of the file rfile'
complete -c truncate -s s -d 'off + | - | % | / size SUFFIX on Xc If the size argument is preceded by a plu…'

