# tty
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man1/tty.1
complete -c tty -s s -d 'Do not write the terminal name; only the exit status is affected when this op…'

