# ul
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man1/ul.1
complete -c ul -s i -d 'Underlining is indicated by a separate line containing appropriate dashes \\-'
complete -c ul -s t -d 'Overrides the terminal type specified in the environment with terminal'

