# visudo
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man8/visudo.8
complete -c visudo -l with-editor -d 'configure option'
complete -c visudo -l with-env-editor -d 'configure option'
complete -c visudo -s c -l check -d 'Enable check-only mode'
complete -c visudo -s O -d and
complete -c visudo -s P -d 'options)'
complete -c visudo -s q -d 'option was specified'
complete -c visudo -s f -l file -d 'Specify an alternate sudoers file location, see below.  As of version 1. 8'
complete -c visudo -s h -l help -d 'Display a short help message to the standard output and exit'
complete -c visudo -s I -l no-includes -d 'Disable the editing of include files unless there is a pre-existing syntax er…'
complete -c visudo -l owner -d 'Enforce the default ownership (user and group) of the sudoers file'
complete -c visudo -l perms -d 'Enforce the default permissions (mode) of the sudoers file'
complete -c visudo -l quiet -d 'Enable quiet mode.  In this mode details about syntax errors are not printed'
complete -c visudo -s s -l strict -d 'Enable strict checking of the sudoers file'
complete -c visudo -s V -l version -d 'Print the visudo and sudoers grammar versions and exit'

