# vmmap
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man1/vmmap.1
complete -c vmmap -s s -d 'Print sorted regions and malloc zones by size (dirty + swapped)'
complete -c vmmap -s w -d 'Print wide output, to show full paths of mapped files'
complete -c vmmap -s v -d 'Equivalent to w submap allSplitLibs noCoalesce'
complete -c vmmap -o pages -d 'Print region sizes in page counts rather than kilobytes'
complete -c vmmap -o interleaved -d 'Print all regions in ascending order of starting address, rather than printin…'
complete -c vmmap -o submap -d 'Print information about VM submaps'
complete -c vmmap -o allSplitLibs -d 'Print information about all shared system split libraries, even those not loa…'
complete -c vmmap -o noCoalesce -d 'Do not coalesce adjacent identical regions'
complete -c vmmap -o summary -d 'Print only the summary of VM usage, not the individual region detail'

