# w
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man1/w.1
complete -c w -s h -d 'Suppress the heading'
complete -c w -s i -d 'Output is sorted by idle time'

